--- #YAML:1.0
name:               Geo-Coder-SimpleGeo
version:            0.05
abstract:           Geocode addresses with the SimpleGeo API
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    Encode:          0
    JSON:            2
    LWP::UserAgent:  6.02
    URI:             1.36
resources:
    repository:  http://github.com/gray/geo-coder-simplegeo
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    JSON::XS:             2
    LWP::Protocol::https:  6.02
